diff --git a/Makefile b/Makefile
index 0b5738b..350c2d3 100644
--- a/Makefile
+++ b/Makefile
@@ -41,7 +41,7 @@ DIRS = $(DESTDIR)$(bindir) $(DESTDIR)$(compdir) \
 
 
 # INSTALL scripts 
-INSTALL         = install -p --verbose 
+INSTALL         = install -p
 INSTALL_BIN     = $(INSTALL) -m 755 
 INSTALL_DIR     = $(INSTALL) -m 755 -d 
 INSTALL_DATA    = $(INSTALL) -m 644 
diff --git a/bin/Makefile b/bin/Makefile
index 8e0a7e2..5d0c3b4 100644
--- a/bin/Makefile
+++ b/bin/Makefile
@@ -28,7 +28,7 @@ DIRS = $(DESTDIR)$(bindir) $(DESTDIR)/etc $(DESTDIR)$(pkgdatadir)
 
 
 # INSTALL scripts 
-INSTALL         = install -p --verbose 
+INSTALL         = install -p
 INSTALL_BIN     = $(INSTALL) -m 755 
 INSTALL_DIR     = $(INSTALL) -m 755 -d 
 INSTALL_DATA    = $(INSTALL) -m 644 
diff --git a/docs/Makefile b/docs/Makefile
index 2e70622..c73f1d5 100644
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -28,7 +28,7 @@ DIRS = $(DESTDIR)$(bindir) $(DESTDIR)/etc $(DESTDIR)$(pkgdatadir) $(DESTDIR)$(ma
 
 
 # INSTALL scripts 
-INSTALL         = install -p --verbose 
+INSTALL         = install -p
 INSTALL_BIN     = $(INSTALL) -m 755 
 INSTALL_DIR     = $(INSTALL) -m 755 -d 
 INSTALL_DATA    = $(INSTALL) -m 644 
